/**
 * Starter-content constraint verifier (#316).
 *
 *   npx tsx scripts/verify-starter-content.ts --lang es
 *
 * Proves a pack's starter series keeps its promises, using the app's own
 * machinery at every step: lessons are tokenized with the shared tokenizer
 * (languages/tokenizer), tokens folded with foldWord, and resolved against the
 * on-device dictionary exactly like lookupWord's static path (exact headword →
 * inflection→lemma; the AI-cache fallthrough deliberately doesn't count).
 *
 * Hard failures (exit 1): unresolvable tokens (dead taps), off-list lemmas,
 * out-of-band lemmas, and per-lesson new-lemma caps. Coverage and recycling
 * are reported always and enforced when --require-coverage / --require-recycles
 * are given (CI can hold a shipped series to its bar).
 *
 * Manifest knobs (all optional, alongside the #315 fields):
 *   { "allow": ["ana"], "maxNewLemmasPerLesson": 60,
 *     "lessons": [{ "file": "01-x.md", "title": "X", "maxRank": 250, "allow": ["toto"] }] }
 * Without per-lesson maxRank, caps ramp by band (see defaultLessonCaps).
 *
 * Needs data/dictionary-<lang>.db (fetch per dict.env) and a wordlist.json
 * generated by scripts/gen-starter-wordlist.py.
 */

import Database from 'better-sqlite3';
import fs from 'fs';
import path from 'path';
import { LANGUAGES, isValidLanguageCode } from '../languages/registry';
import { foldWord, normalizeText } from '../languages/text';
import { tokenizeWords } from '../languages/tokenizer';
import {
  defaultLessonCaps,
  verify,
  type LessonTokens,
  type Resolver,
  type WordlistEntry,
} from './starter/verify-core';

const REPO = path.resolve(__dirname, '..');

interface ManifestLesson {
  file: string;
  title: string;
  maxRank?: number;
  allow?: string[];
  maxNewLemmas?: number;
}
interface Manifest {
  title: string;
  lessons: ManifestLesson[];
  allow?: string[];
  maxNewLemmasPerLesson?: number;
}

function arg(name: string): string | undefined {
  const i = process.argv.indexOf(`--${name}`);
  return i >= 0 ? process.argv[i + 1] : undefined;
}

const lang = arg('lang');
if (!lang || !isValidLanguageCode(lang)) {
  console.error('usage: npx tsx scripts/verify-starter-content.ts --lang <code>');
  console.error('       [--dir <starter dir>] [--wordlist <json>] [--dict <db>]');
  console.error('       [--require-coverage <pct>] [--require-recycles <n>]');
  process.exit(2);
}
const pack = LANGUAGES[lang];

const dir = arg('dir') ?? path.join(REPO, 'languages', lang, 'content', 'starter');
const wordlistPath = arg('wordlist') ?? path.join(dir, 'wordlist.json');
const dictPath = arg('dict') ?? path.join(REPO, 'data', `dictionary-${lang}.db`);
const requireCoverage = arg('require-coverage') ? Number(arg('require-coverage')) : null;
const requireRecycles = arg('require-recycles') ? Number(arg('require-recycles')) : null;

for (const [what, p] of [
  ['starter manifest', path.join(dir, 'manifest.json')],
  ['wordlist', wordlistPath],
  ['dictionary', dictPath],
] as const) {
  if (!fs.existsSync(p)) {
    console.error(`missing ${what}: ${p}`);
    process.exit(2);
  }
}

const manifest = JSON.parse(fs.readFileSync(path.join(dir, 'manifest.json'), 'utf8')) as Manifest;
const wordlistFile = JSON.parse(fs.readFileSync(wordlistPath, 'utf8')) as {
  bandSize?: number;
  words: WordlistEntry[];
};
const wordlist = wordlistFile.words;

const foldAll = (words: string[] | undefined) => new Set((words ?? []).map((w) => foldWord(w, pack)));

const caps = defaultLessonCaps(manifest.lessons.length, wordlist.length, wordlistFile.bandSize ?? 250);
const lessons: LessonTokens[] = manifest.lessons.map((lesson, i) => {
  const markdown = normalizeText(fs.readFileSync(path.join(dir, lesson.file), 'utf8'));
  const tokens = tokenizeWords(markdown, pack)
    .map((t) => foldWord(t.text, pack))
    .filter((t) => !/^\d+$/.test(t)); // bare numbers aren't vocabulary
  return {
    title: lesson.title,
    maxRank: lesson.maxRank ?? caps[i],
    allow: foldAll(lesson.allow),
    tokens,
    ...(lesson.maxNewLemmas !== undefined && { maxNewLemmas: lesson.maxNewLemmas }),
  };
});

// The static half of api/src/lib/dictionary-db.ts lookupWord.
const db = new Database(dictPath, { readonly: true, fileMustExist: true });
const selectEntry = db.prepare('SELECT word FROM entries WHERE word = ?');
const selectLemma = db.prepare(
  'SELECT i.lemma FROM inflections i JOIN entries e ON e.word = i.lemma WHERE i.inflected_form = ? LIMIT 1',
);
const resolve: Resolver = (folded) => {
  const exact = selectEntry.get(folded) as { word: string } | null;
  if (exact) return exact.word;
  const infl = selectLemma.get(folded) as { lemma: string } | null;
  return infl ? infl.lemma : null;
};

const summary = verify(lessons, wordlist, resolve, {
  allow: foldAll(manifest.allow),
  ...(manifest.maxNewLemmasPerLesson !== undefined && {
    maxNewLemmasPerLesson: manifest.maxNewLemmasPerLesson,
  }),
});

// ── Report ───────────────────────────────────────────────────────────────────
console.log(`\n${manifest.title} — ${lang} starter verification`);
console.log(`wordlist: ${wordlist.length} lemmas · dictionary: ${path.basename(dictPath)}\n`);
for (const l of summary.lessons) {
  const flag = l.violations.length ? `✗ ${l.violations.length} violation(s)` : '✓';
  console.log(
    `  ${flag}  ${l.title.padEnd(24)} cap ${String(l.maxRank).padStart(4)} · ${l.tokenCount} tokens · +${l.newTargetLemmas.length} new lemmas`,
  );
}

if (summary.violations.length) {
  console.log('\nViolations:');
  for (const v of summary.violations) {
    console.log(`  [${v.lesson}] ${v.kind}: ${v.detail}`);
  }
}

const cov = summary.coverage;
console.log(`\nCoverage: ${cov.introduced}/${cov.reachableTotal} reachable target lemmas introduced (${cov.pct}%)`);
if (cov.missing.length) {
  const preview = cov.missing.slice(0, 15).join(', ');
  console.log(`  never introduced: ${preview}${cov.missing.length > 15 ? ` … +${cov.missing.length - 15} more` : ''}`);
}
if (summary.underRecycled.length) {
  const preview = summary.underRecycled
    .slice(0, 15)
    .map((r) => `${r.lemma}(${r.count})`)
    .join(', ');
  console.log(`Under-recycled (<3): ${preview}${summary.underRecycled.length > 15 ? ` … +${summary.underRecycled.length - 15} more` : ''}`);
}

let failed = summary.violations.length > 0;
if (requireCoverage !== null && cov.pct < requireCoverage) {
  console.log(`\n✗ coverage ${cov.pct}% is below required ${requireCoverage}%`);
  failed = true;
}
if (requireRecycles !== null) {
  const short = summary.underRecycled.filter((r) => r.count < requireRecycles);
  if (short.length) {
    console.log(`\n✗ ${short.length} introduced lemma(s) recycled fewer than ${requireRecycles} times`);
    failed = true;
  }
}

console.log(failed ? '\nFAIL' : '\nPASS');
process.exit(failed ? 1 : 0);
